### ISSUE TITLE
Allow publishing and subscribing without a wrapping element

### ISSUE THREAD

**Issue by itsikbelson-spotlight** [daily-co/daily-opentok-client#41]
We currently use the OpenTok API without a wrapping element both for publish and subscribe.
It will be great to be able to use the shim in the same way (currently we hacked the shim to make it work).
Also, we're listening on `videoElementCreated` event, which is not fired from the shim, and it will be great to get it.

**Comment by jamsea** [comment]
@itsikbelson-spotlight I had a work-in-progress branch for `videoElementCreated` but had to abandon it because it was made before we refactored the codebase. If you figured out a workaround though I'd love to see a PR! Even if it's only half-baked.

**Comment by itsikbelson-spotlight** [comment]
@jamsea we moved away from the shim to do full integration.
